config/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as views_accounts
from aluno.views import (home, create_aluno, update_aluno, delete_aluno, visualizar_perfil, indicacoes)
from indicado.views import (create_indicado, update_indicado, delete_indicado)


app_name = 'aluno'


urlpatterns = [
    #USUERIO E ADMIN
    path('admin/', admin.site.urls),
	path('Mais_Amigos_Mais_Descontos/', views_accounts.registerPage, name="registerPage"),
	path('login/', views_accounts.loginPage, name="login"),  
	path('logout/', views_accounts.logoutUser, name="logout"),
    path('entrar/', views_accounts.loginAPI, name="loginAPI"), 

    #ALUNO
	path('', home, name='home'),
    path('meus-dados/aluno/', create_aluno, name='create_aluno'),
    path('meus-dados/<str:profile>/', create_aluno, name='create_aluno'),
    path('atualizar/<str:user>/', update_aluno, name='update_aluno'),
    path('profile/<str:user>/', visualizar_perfil, name='visualizar_perfil'),
    path('apagar/aluno-<int:id>/', delete_aluno, name='delete_aluno'),

    #INDICADO
    path('indique-um-amigo/', create_indicado, name='create_indicado'),
    path('indicado/update/<int:id>/', update_indicado, name='update_indicado'),
    path('indicado/delete/<int:id>/', delete_indicado, name='delete_indicado'),
    path('minhas-indicacoes/', indicacoes, name='indicacoes'),
]

#ADMINISTRATIVE
admin.site.index_title = 'Luiz Henrique Chaves'
admin.site.site_title = 'Administrativo'
admin.site.site_header = 'Luiz Henrique'

aluno/models.py
from django.db import models
from curso.models import Curso

class Aluno(models.Model):
    nome_do_aluno = models.CharField(max_length=50)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    periodo = models.CharField(max_length=50)
    matricula = models.CharField(max_length=50)
    id_usuario = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.nome_do_aluno

#example filter
#article = Article.objects.get(pk=1)

indicado/models.py
from django.db import models
from bonus.models import Bonus
from curso.models import Curso


class Indicado(models.Model):
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=50)
    curso_pretendido = models.ForeignKey(Curso, on_delete=models.CASCADE)
    email = models.CharField(max_length=150)
    bonus = models.ForeignKey(Bonus, on_delete=models.CASCADE)
    CHOICES = (
        ('Pendente', 'Pendente'),
        ('Matriculado', 'Matriclado'),
    )
    status = models.CharField(max_length=100, choices = CHOICES, default='Pendente')
    id_usuario = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

aluno/forms.py
from django import forms
from aluno.models import Aluno

class AlunoForm(forms.ModelForm):
	class Meta:
            model = Aluno
            fields = ['nome_do_aluno','curso', 'periodo','matricula','id_usuario']
            widgets = {'id_usuario': forms.HiddenInput(attrs=None)}

indicado/forms.py
from django import forms
from indicado.models import Indicado

class IndicadoForm(forms.ModelForm):
	class Meta:
		model = Indicado
		fields = [
                  'nome',
                  'telefone',
                  'curso_pretendido',
                  'email',
                  'bonus',
                  'id_usuario',
            ]

aluno/views.py
from django.shortcuts import render, redirect
from aluno.models import Aluno
from aluno.forms import AlunoForm
from indicado.models import Indicado
from django.contrib.auth.decorators import login_required

USUARIO = dict()

@login_required(login_url='login')
def home(request):
    
    indicados = Indicado.objects.filter(id_usuario=request.user)
    if Aluno.objects.filter(id_usuario=request.user):
        return render(request, 'accounts/inicio.html', {'indicados': indicados})
    else:
        return redirect('create_aluno', profile=str(request.user))

@login_required(login_url='login')
def indicacoes(request):    
    indicados = Indicado.objects.filter(id_usuario=request.user)
    if Aluno.objects.filter(id_usuario=request.user):
        return render(request, 'indicacoes.html', {'indicados': indicados})
    else:
        return redirect('create_aluno', profile=str(request.user))
    

@login_required(login_url='login')
def create_aluno(request, **kwargs):
    global USUARIO
    USUARIO['USER'] = str(request.user)
    USUARIO['ID'] = request.user.id

    if Aluno.objects.filter(id_usuario=request.user):
        aluno = Aluno.objects.get(id_usuario=request.user)
        return redirect('home')
    else: 
        form = AlunoForm(request.POST or None)   
        if request.method == 'POST':
            print(form.__dict__)            
            if form.is_valid():
                # se form é valido mas não está salvando, 
                # é porque o banco está limitando a quantidade de caracteres a ser salvo
                #modificar essa informação em models
                form.save()
                return redirect('home')         
        return render(request, 'aluno-form.html', {'form': form})

@login_required(login_url='login')
def update_aluno(request, user):
    if str(user) == str(request.user):
        aluno = Aluno.objects.get(id_usuario=user)
        alunos = Aluno.objects.get(id=aluno.id)
        form = AlunoForm(request.POST or None, instance=alunos)
        if form.is_valid():
            form.save()
            return redirect('home')
            
    else:
        return redirect('home')
    
    return render(request, 'aluno-form.html', {'form': form, 'aluno': alunos})

@login_required(login_url='login')
def visualizar_perfil(request, user):
    indicados_cont = len(Indicado.objects.filter(id_usuario=request.user))
    matriculados_cont = len(Indicado.objects.filter(status="Matriculado"))
    pendentes_cont = len(Indicado.objects.filter(status="Pendente"))

    if str(user) == str(request.user): #impedindo que usuários vejam perfis de outros usuários
        if Aluno.objects.filter(id_usuario=request.user):
            aluno = Aluno.objects.get(id_usuario=user)
        else:
            return redirect('create_aluno', profile=str(request.user))
    else:
        return redirect('home')

    return render(request, 'profile.html', {'aluno': aluno, 'indicados_cont': indicados_cont, 'matriculados_cont': matriculados_cont, 'pendentes_cont': pendentes_cont})

@login_required(login_url='login')
def delete_aluno(request, id):
    aluno = Aluno.objects.get(id=id)
    if request.method == 'POST':
        aluno.delete()
        return redirect('home')
    return render(request, 'aluno-delete-confirm.html', {'aluno': aluno})

indicado/views.py
from django.shortcuts import render, redirect
from indicado.models import Indicado
from indicado.forms import IndicadoForm
from django.contrib.auth.decorators import login_required

#ModelName.objects.filter(id=id).update(status='closed')
#exemplo de manipulação de model

@login_required(login_url='login')
def create_indicado(request, **kwargs):
    indicados_cont = len(Indicado.objects.filter(id_usuario=request.user))
    if indicados_cont < 10:
        form = IndicadoForm(request.POST or None)   
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                return redirect('indicacoes')
    else:
        return render(request, 'aviso.html')

    return render(request, 'indicado-form.html', {'form': form})

@login_required(login_url='login')
def update_indicado(request, id):
    indicado = Indicado.objects.get(id=id)
    if str(indicado.id_usuario) == str(request.user):
        #impede que o usuário edite informações de indicados de outros alunos
        form = IndicadoForm(request.POST or None, instance=indicado)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        redirect('home')
    return render(request, 'indicado-form.html', {'form': form, 'indicados': indicado })

@login_required(login_url='login')
def delete_indicado(request, id):
    indicado = Indicado.objects.get(id=id)
    if request.method == 'POST':
        indicado.delete()
        return redirect('home')
    return render(request, 'indicado-delete-confirm.html', {'indicado': indicado})

indicado/templates/aluno-form.html
<!doctype html>
<html lang="pt-br">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Perfil</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/checkout/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets\bootstrap\css\bootstrap.min.v4.3.1.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
    
  </head>

  <body class="bg-light">
    {%  include 'accounts/Main-Bootstrap-v5.0.html' %}
    <div class="container">
      <div class="py-5 text-center">
        <h2>Mais Amigos Mais Descontos</h2>
        <p class="lead">A FATEPI se preocupa muito com a segurança de dados dos seus Alunos</p>
      </div>

      <div class="row">

        <style type="text/css">
      input[type="text"]{
        width: 100%;
        border-top: 0px solid;
        border-left: 0px solid;
        border-right: 0px solid;
        border-bottom: 1px solid silver;
      }
      #form-container{
        width: 800px;
      }
      .col-lg-6.col-md-12 {
        margin-top: 21px !important;
      }
    </style>


    {% load crispy_forms_tags %} 

    <div id="form-container" class="container">
      <h4>INDIQUE UM ESTUDANTE</h4><br/>
      
      <form method="post">
          {% csrf_token %}
          <div class="row">

            <div class="col-lg-6 col-md-12">
              {{form.nome|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.telefone|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.curso_pretendido|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.email|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.bonus|as_crispy_field}}
            </div>

            <input type="hidden" name="id_usuario" id="id_id_usuario" value="{{ request.user }}">

          </div>
        <br/>       
        <button type="submit" class="btn btn-primary" >Salvar</button>
        </form>
        {% for message in messages %}
          <p id="messages">{{message}}</p>
        {% endfor %}
      </div>

      {% if product %}
        <a href="{% url 'delete_indicado' indicado.id %}">Delete</a>
      {% endif %}
        
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">FATEPI FAESPI</p>
        
      </footer>
    </div>

    
    
  </body>
</html>

indicado/templates/aviso.html
<!doctype html>
<html lang="pt-br">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Perfil</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/checkout/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets\bootstrap\css\bootstrap.min.v4.3.1.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
    
  </head>

  <body class="bg-light">
    {%  include 'accounts/Main-Bootstrap-v5.0.html' %}
    
      <div class="container">
      <h1>Você atingiu o limite de indicações para este semestre!</h1>
      </div>
      <footer class="my-5 pt-5 text-muted text-center text-small" >
        <p class="mb-1">FATEPI FAESPI</p>
        
      </footer>
    </div>

    
    
  </body>
</html>

indicado/templates/indicado-delete-confirm.html
{%  extends 'accounts/Main-Bootstrap-v5.0.html' %}

{% block content %}
<div class="container" style="margin-top: 5%;">
    <form method="post">
        {% csrf_token %}
        <h2>Deseja apagar o indicado '{{ indicado.nome }}' ?</h2>
        <button class="btn btn-sm btn-info" type="submit">Apagar</button>
    </form>
</div>
{% endblock %}

indicado/templates/indicado-form.html
<!doctype html>
<html lang="pt-br">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Perfil</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/checkout/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets\bootstrap\css\bootstrap.min.v4.3.1.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
    
  </head>

  <body class="bg-light">
    {%  include 'accounts/Main-Bootstrap-v5.0.html' %}
    <div class="container">
      <div class="py-5 text-center">
        <h2>Mais Amigos Mais Descontos</h2>
        <p class="lead">A FATEPI se preocupa muito com a segurança de dados dos seus Alunos</p>
      </div>

      <div class="row">

        <style type="text/css">
      input[type="text"]{
        width: 100%;
        border-top: 0px solid;
        border-left: 0px solid;
        border-right: 0px solid;
        border-bottom: 1px solid silver;
      }
      #form-container{
        width: 800px;
      }
      .col-lg-6.col-md-12 {
        margin-top: 21px !important;
      }
    </style>


    {% load crispy_forms_tags %} 

    <div id="form-container" class="container">
      <h4>INDIQUE UM AMIGO</h4><br/>
      
      <form method="post">
          {% csrf_token %}
          <div class="row">

            <div class="col-lg-6 col-md-12">
              {{form.nome|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.telefone|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.curso_pretendido|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.email|as_crispy_field}}
            </div>

            <div class="col-lg-6 col-md-12">
              {{form.bonus|as_crispy_field}}
            </div>

            <input type="hidden" name="id_usuario" id="id_id_usuario" value="{{ request.user }}">

          </div>
        <br/>       
        <button type="submit" class="btn btn-primary" >Salvar</button>
        </form>
        {% for message in messages %}
          <p id="messages">{{message}}</p>
        {% endfor %}
      </div>

      {% if product %}
        <a href="{% url 'delete_indicado' indicado.id %}">Delete</a>
      {% endif %}
        
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">FATEPI FAESPI</p>
        
      </footer>
    </div>

    
    
  </body>
</html>

indicado/templates/indicado.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Alunos</title>
</head>
<body>
    <ul>
        {% for product in products %}
            <a href="{% url 'update_aluno' aluno.id %}">
                <li> {{ aluno.nome }}</li>
            </a>
        {% endfor %}
    </ul>

    <a href="{% url 'create_aluno' %}">New product</a>
</body>
</html>

indicado/templates/profile.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Perfil</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/checkout/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets\bootstrap\css\bootstrap.min.v4.3.1.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
  </head>

  <body class="bg-light">
    {%  include 'navbar.html' %}
    <div class="container">
      <div class="py-5 text-center">
        <h2>Mais Amigos Mais Descontos</h2>
        <p class="lead">A FATEPI se preocupa muito com a segurança de dados dos seus Alunos</p>
      </div>

      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">A Faculdade de Tecnologia do Piauí é uma instituição de ensino superior privada pertencente ao Grupo Magister de Ensino</span>
            
          </h4>
          
        </div>


        
        <div class="col-md-8 order-md-1">
          <div class="container">
          <ul class="list-group mb-8">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Nome Completo</h6>
                <small class="text-muted">{{aluno.nome_do_aluno}}</small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Curso</h6>
                <small class="text-muted">{{aluno.curso}}</small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Matricula</h6>
                <small class="text-muted">{{aluno.matricula}}</small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Periodo</h6>
                <small class="text-muted">{{aluno.periodo}}</small>
              </div>
            </li>
            <!--
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <small>Você está protegido</small>
              </div>
            </li>
            -->
          </ul>
            
            <hr class="mb-4">
            <a href='/atualizar/{{request.user}}' class="btn btn-primary btn-lg btn-block" type="submit">Editar</a>
          </div>
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">FATEPI FAESPI</p>
        
      </footer>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>
</html>